<?php ob_start(); ?>
	<h1 class="heading-green">Our Commitment to Your Privacy</h1>
	<p>The M-Pro Corporation respects your privacy. We are particularly sensitive to privacy issues on the Internet and therefore we provide this Privacy Policy so you know about your online information practices and understand how we treat information we receive about you from the Internet.</p>
	<h2 class="heading-green">The Information We Collect</h2>
	<p>In general, you can browse our Web site without telling us who you are or revealing any personal information about yourself. We are, however, able to determine your IP address. We use your IP address to help diagnose problems with our server, to administer our Web site, to measure the use of our Web site and to improve the content of our Web site. In short we use your IP to gather aggregate demographic information. There are a few places where we give you an opportunity to provide us your personal information. This refers to information that lets us know the specifics of who you are. When you engage in certain activities on our web site, such as ordering a product, filling out a survey or sending us feedback, we may ask you to provide certain information.
	If you choose to share any personal information with us, you will see that the amount and type of personal information we request depends on how you use our website. It is completely optional for you to engage in these activities. If you elect to engage in these activities, however, we may ask that you provide us personal information, such as your first and last name, mailing address (including zip code), email address, telephone and facsimile numbers, and other personal identifying information. When ordering products on our website, you may be asked to provide a credit card number. Depending upon the activity, some of the information we may ask you to provide is identified as mandatory and some as voluntary. If you do no provide the mandatory data with respect to a particular activity, you will not be able to engage in that activity.</p>
	<p>Additionally our website employs the use of cookies in certain areas. Cookies are small bits of information stored on your browser. Cookies enable browsers to "remember" information related to a specific user, and also improve navigational reliability within a given site. The use of cookies allows us to recognize you every time you visit and to personalize our website to better suit your needs. If you are uncomfortable with storing cookies on your browser, you may set your browser to specifically reject cookies. </p>
	<h2 class="heading-green">The Way We Use Information</h2>
	<p>We may use your personal information for particular purposes such as processing your order or for marketing research and other marketing purposes and for providing you with the latest product and promotional information that might be useful to you. We may use your personal information to deliver information to you and to contact you regarding administrative notices. We may share this information with M-Pro's affiliates, and other business partners to support your customer relationship with M-Pro Corporation. We must release your credit card information to credit-issuing bank to confirm payment for products purchased on our website; release your address information to third parties that help us provide customer service. We will not give or sell this information to any other company for its use in marketing or solicitation.</p>
	<h2 class="heading-green">Our Commitment to Security of Your Personal Information</h2>
	<p>We want you to have continuing trust in the M-Pro Corporation and its products, so, we have put in place reasonable physical, electronic and managerial procedures to safeguard and secure your personal information.</p>
	<p>In order to most effectively serve you, credit card transactions and order fulfillment are handled by established third party banking, processing agents and distribution institutions. They receive the information needed to verify and authorize your credit card or other payment information to process and ship your order.</p>
	<p>Unfortunately, no data transmission over the Internet or any wireless network can be guaranteed 100% secure. As a result, while we strive to protect your personal information, you acknowledge that: (a) there are security and privacy limitations of the Internet which are beyond our control; (b) the security, integrity and privacy of any and all information and data exchanged between you and us through our website cannot be guaranteed; and (c) any such information and data may be viewed or tampered with by a third party.</p>
	<p>By using this Web site you are agreeing to the terms of the M-Pro Privacy Policy. We reserve the right to modify our privacy policy as business needs require. We will post changes to our Web site.</p>

<?php	
//  Assign all Page Specific variables
$pagemaincontent = ob_get_contents(); 
ob_end_clean();
$pagetitle = "M-ProInc - Trimmer Trolley - Privacy Policy";
include("master.php");
?>